# frozen_string_literal: true

source 'https://rubygems.org'

ruby File.read('.ruby-version').chomp

gem 'bundler'
gem 'pg'
gem 'puma', '~> 4.3'
gem 'rails', '~> 6.0.3', '>= 6.0.3.4'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false
gem 'faker'
gem 'friendly_id'
gem 'js-routes', '>= 1.4.10', git: 'https://github.com/railsware/js-routes'
gem 'oj'
gem 'rack-cors'

group :development, :test do
  gem 'awesome_print', require: false
  gem 'brakeman', require: false
  gem 'dotenv-rails'
  gem 'factory_bot_rails'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rspec-rails'
end

group :development do
  gem 'binding_of_caller'
  gem 'listen', '~> 3.2'
  gem 'overcommit', require: false
  gem 'rubocop', '~> 0.9', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'database_cleaner-active_record'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
end
